# generated by datamodel-codegen:
#   filename:  directives.graphql
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import TypeAliasType

Boolean = TypeAliasType("Boolean", bool)
"""
The `Boolean` scalar type represents `true` or `false`.
"""


ID = TypeAliasType("ID", str)
"""
The `ID` scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as `"4"`) or integer (such as `4`) input value will be accepted as an ID.
"""


Int = TypeAliasType("Int", int)
"""
The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1.
"""


String = TypeAliasType("String", str)
"""
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
"""


class Color(Enum):
    BLUE = 'BLUE'
    GREEN = 'GREEN'
    RED = 'RED'

    @classmethod
    def graphql_directives(cls) -> list[dict[str, object]]:
        return [
            {'name': 'sensitive', 'arguments': {'role': 'enum'}, 'location': 'ENUM'}
        ]

    @classmethod
    def graphql_enum_value_directives(cls) -> dict[str, list[dict[str, object]]]:
        return {
            'BLUE': [
                {
                    'name': 'sensitive',
                    'arguments': {'role': 'blue'},
                    'location': 'ENUM_VALUE',
                }
            ],
            'RED': [
                {
                    'name': 'tags',
                    'arguments': {'values': ['warm', 'stop']},
                    'location': 'ENUM_VALUE',
                }
            ],
        }


class Node(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={
            'directives': [
                {
                    'name': 'sensitive',
                    'arguments': {'role': 'node'},
                    'location': 'INTERFACE',
                }
            ]
        },
    )
    id: ID = Field(
        ...,
        json_schema_extra={
            'directives': [
                {
                    'name': 'sensitive',
                    'arguments': {'role': 'id'},
                    'location': 'FIELD_DEFINITION',
                }
            ]
        },
    )
    typename__: Literal['Node'] | None = Field('Node', alias='__typename')


class User(Node):
    model_config = ConfigDict(
        json_schema_extra={
            'directives': [
                {
                    'name': 'sensitive',
                    'arguments': {'role': 'user'},
                    'location': 'OBJECT',
                }
            ]
        },
    )
    friends: list[User] | None = Field(
        None,
        json_schema_extra={
            'directives': [
                {
                    'name': 'paginated',
                    'arguments': {'limit': 50},
                    'location': 'FIELD_DEFINITION',
                }
            ]
        },
    )
    name: String | None = Field(
        None,
        json_schema_extra={
            'directives': [
                {
                    'name': 'sensitive',
                    'arguments': {'role': 'name'},
                    'location': 'FIELD_DEFINITION',
                },
                {
                    'name': 'deprecated',
                    'arguments': {'reason': 'use fullName'},
                    'location': 'FIELD_DEFINITION',
                },
            ]
        },
    )
    typename__: Literal['User'] | None = Field('User', alias='__typename')


class UserInput(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={
            'directives': [
                {
                    'name': 'sensitive',
                    'arguments': {'role': 'input'},
                    'location': 'INPUT_OBJECT',
                }
            ]
        },
    )
    name: String = Field(
        ...,
        json_schema_extra={
            'directives': [
                {
                    'name': 'sensitive',
                    'arguments': {'role': 'iname'},
                    'location': 'INPUT_FIELD_DEFINITION',
                }
            ]
        },
    )
    typename__: Literal['UserInput'] | None = Field('UserInput', alias='__typename')


User.model_rebuild()
