# generated by datamodel-codegen:
#   filename:  directives.graphql
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field
from typing_extensions import TypeAliasType

Boolean = TypeAliasType("Boolean", bool)
"""
The `Boolean` scalar type represents `true` or `false`.
"""


ID = TypeAliasType("ID", str)
"""
The `ID` scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as `"4"`) or integer (such as `4`) input value will be accepted as an ID.
"""


Int = TypeAliasType("Int", int)
"""
The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1.
"""


String = TypeAliasType("String", str)
"""
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
"""


class Color(Enum):
    BLUE = 'BLUE'
    GREEN = 'GREEN'
    RED = 'RED'


class Node(BaseModel):
    id: ID
    typename__: Literal['Node'] | None = Field('Node', alias='__typename')


class User(Node):
    friends: list[User] | None = None
    name: String | None = None
    typename__: Literal['User'] | None = Field('User', alias='__typename')


class UserInput(BaseModel):
    name: String
    typename__: Literal['UserInput'] | None = Field('UserInput', alias='__typename')


User.model_rebuild()
