# generated by datamodel-codegen:
#   filename:  subscription_scope.graphql

from __future__ import annotations

from enum import Enum
from typing import Literal, Union

from pydantic import BaseModel, Field
from typing_extensions import TypeAliasType

Boolean = TypeAliasType("Boolean", bool)
"""
The `Boolean` scalar type represents `true` or `false`.
"""


ID = TypeAliasType("ID", str)
"""
The `ID` scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as `"4"`) or integer (such as `4`) input value will be accepted as an ID.
"""


Int = TypeAliasType("Int", int)
"""
The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1.
"""


String = TypeAliasType("String", str)
"""
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
"""


class EventKind(Enum):
    ARCHIVED = 'ARCHIVED'
    CREATED = 'CREATED'
    UPDATED = 'UPDATED'


class Node(BaseModel):
    id: ID
    typename__: Literal['Node'] | None = Field('Node', alias='__typename')


class Alert(Node):
    id: ID
    level: Int | None = None
    typename__: Literal['Alert'] | None = Field('Alert', alias='__typename')


class Story(Node):
    id: ID
    title: String
    typename__: Literal['Story'] | None = Field('Story', alias='__typename')


class SubscriptionStoryArguments(BaseModel):
    id: ID


class EventFilter(BaseModel):
    keyword: String | None = None
    kinds: list[EventKind] | None = None
    typename__: Literal['EventFilter'] | None = Field('EventFilter', alias='__typename')


Event = TypeAliasType(
    "Event",
    Union[
        'Alert',
        'Story',
    ],
)


class Subscription(Node):
    alerts: list[Alert] | None = None
    events: list[Event]
    id: ID
    story: Story | None = None
    typename__: Literal['Subscription'] | None = Field(
        'Subscription', alias='__typename'
    )


class SubscriptionEventsArguments(BaseModel):
    filter: EventFilter | None = None
    kind: EventKind
    limit: Int | None = 20
