# generated by datamodel-codegen:
#   filename:  schema_validators_not.json

from __future__ import annotations

from collections.abc import Mapping as _Mapping
from enum import Enum
from typing import Annotated, Any, ClassVar, Literal, get_args

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    TypeAdapter,
    ValidationError,
    model_validator,
)


class _JsonSchemaRuntimeValidationBase(BaseModel):
    __json_schema_not_rules__: ClassVar[tuple[Any, ...]] = ()

    @model_validator(mode='before')
    @classmethod
    def _validate_json_schema_runtime_rules(cls, data: Any) -> Any:
        return data

    @model_validator(mode='after')
    def _validate_json_schema_not_rules(self) -> Any:
        rules = type(self).__json_schema_not_rules__
        if not rules:
            return self
        matched: list[int] = []
        for index, rule in enumerate(rules):
            value = self.root if rule['root_value'] else self
            if self._json_schema_not_matches(index, rule['branch'], value):
                matched.append(index)
        if matched:
            raise ValueError(
                'Value matches a forbidden JSON Schema \'not\' branch: '
                + ', '.join(str(index) for index in matched)
            )
        return self

    @classmethod
    def _json_schema_not_matches(cls, index: int, branch: Any, value: Any) -> bool:
        adapters = cls.__dict__.get('_json_schema_not_adapters__')
        if adapters is None:
            adapters = {}
            cls._json_schema_not_adapters__ = adapters
        adapter = adapters.get(index)
        if adapter is None:
            adapter = cls._json_schema_not_build_adapter(branch)
            adapters[index] = adapter
        data = cls._json_schema_not_data(value)
        try:
            adapter.validate_python(data, strict=True)
            return True
        except ValidationError:
            pass
        try:
            validated = adapter.validate_python(data)
        except ValidationError:
            return False
        # Lax validation may coerce values (e.g. "5" to 5); a branch matches
        # only when every validated key round-trips without changing the data.
        return cls._json_schema_not_satisfies(
            data, cls._json_schema_not_data(validated)
        )

    @classmethod
    def _json_schema_not_build_adapter(cls, branch: Any) -> TypeAdapter:
        # Same-module forward references are all defined by the time the first
        # value is validated; rebuild incomplete branch models before adapting.
        for candidate in cls._json_schema_not_branch_types(branch):
            if getattr(candidate, '__pydantic_complete__', None) is False:
                candidate.model_rebuild(force=True)
        return TypeAdapter(branch)

    @classmethod
    def _json_schema_not_branch_types(cls, branch: Any) -> Any:
        yield branch
        for argument in get_args(branch):
            yield from cls._json_schema_not_branch_types(argument)

    @classmethod
    def _json_schema_not_data(cls, value: Any) -> Any:
        # Keep only explicitly provided fields so that defaults fabricated for
        # optional fields cannot satisfy required-presence branches.
        if getattr(type(value), '__pydantic_root_model__', False):
            return cls._json_schema_not_data(value.root)
        if isinstance(value, BaseModel):
            result = {}
            model_type = type(value)
            for field_name in value.__pydantic_fields_set__:
                field = model_type.model_fields.get(field_name)
                # Names provided for extra fields also land in fields_set;
                # they are emitted from __pydantic_extra__ below.
                if field is None:
                    continue
                key = field.alias or field_name
                result[key] = cls._json_schema_not_data(getattr(value, field_name))
            if value.__pydantic_extra__:
                for key, item in value.__pydantic_extra__.items():
                    result[key] = cls._json_schema_not_data(item)
            return result
        if isinstance(value, (list, tuple)):
            return [cls._json_schema_not_data(item) for item in value]
        if isinstance(value, dict) or isinstance(value, _Mapping):
            return {key: cls._json_schema_not_data(item) for key, item in value.items()}
        return value

    @classmethod
    def _json_schema_not_satisfies(cls, raw: Any, validated: Any) -> bool:
        # JSON Schema treats a branch constraint as a subset condition: extra
        # properties on the input are allowed unless the branch forbids them.
        if isinstance(raw, bool) or isinstance(validated, bool):
            return (
                isinstance(raw, bool)
                and isinstance(validated, bool)
                and raw == validated
            )
        if isinstance(raw, Enum):
            raw = raw.value
        if isinstance(validated, Enum):
            validated = validated.value
        if raw is None or validated is None:
            return raw is None and validated is None
        if isinstance(raw, (int, float)) and isinstance(validated, (int, float)):
            return raw == validated
        if isinstance(raw, str) and isinstance(validated, str):
            return raw == validated
        if isinstance(validated, (list, tuple)):
            return (
                isinstance(raw, (list, tuple))
                and len(raw) == len(validated)
                and all(
                    cls._json_schema_not_satisfies(a, b) for a, b in zip(raw, validated)
                )
            )
        if isinstance(validated, dict):
            return (
                isinstance(raw, dict)
                and validated.keys() <= raw.keys()
                and all(
                    cls._json_schema_not_satisfies(raw[key], value)
                    for key, value in validated.items()
                )
            )
        try:
            comparison = raw == validated
        except Exception:
            return False
        return comparison if type(comparison) is bool else False


class CompositionFieldNot0(RootModel[int]):
    root: Annotated[int, Field(ge=100)]


class CompositionFieldNot01(Enum):
    forbidden = 'forbidden'


class CompositionField(_JsonSchemaRuntimeValidationBase, RootModel[Any]):
    __json_schema_not_rules__: ClassVar[tuple[Any, ...]] = (
        {'branch': CompositionFieldNot0 | CompositionFieldNot01, 'root_value': True},
    )

    root: Any


class PresenceFieldNot0(BaseModel):
    a: Any


class PresenceFieldNot1(BaseModel):
    b: Any


class PresenceField(_JsonSchemaRuntimeValidationBase):
    model_config = ConfigDict(
        extra='allow',
    )

    __json_schema_not_rules__: ClassVar[tuple[Any, ...]] = (
        {'branch': PresenceFieldNot0, 'root_value': False},
        {'branch': PresenceFieldNot1, 'root_value': False},
    )

    a: int | None = None
    b: int | None = None


class UserName(_JsonSchemaRuntimeValidationBase, RootModel[str]):
    __json_schema_not_rules__: ClassVar[tuple[Any, ...]] = (
        {'branch': Literal['admin'], 'root_value': True},
    )

    root: str


class NotRootNot0(BaseModel):
    neverField: Any


class BannedShape(BaseModel):
    status: Literal['banned']


class SecretString(RootModel[str]):
    root: Annotated[str, Field(pattern='^secret-')]


class DirectObject(_JsonSchemaRuntimeValidationBase):
    model_config = ConfigDict(
        extra='allow',
    )

    __json_schema_not_rules__: ClassVar[tuple[Any, ...]] = (
        {'branch': BannedShape, 'root_value': False},
    )

    status: str


class ScalarField(_JsonSchemaRuntimeValidationBase, RootModel[str]):
    __json_schema_not_rules__: ClassVar[tuple[Any, ...]] = (
        {'branch': SecretString, 'root_value': True},
    )

    root: str


class ItemsFieldItem(_JsonSchemaRuntimeValidationBase):
    model_config = ConfigDict(
        extra='allow',
    )

    __json_schema_not_rules__: ClassVar[tuple[Any, ...]] = (
        {'branch': BannedShape, 'root_value': False},
    )

    status: str


class NotRoot(_JsonSchemaRuntimeValidationBase):
    model_config = ConfigDict(
        extra='allow',
    )

    __json_schema_not_rules__: ClassVar[tuple[Any, ...]] = (
        {'branch': NotRootNot0, 'root_value': False},
    )

    directObject: DirectObject
    scalarField: ScalarField
    itemsField: list[ItemsFieldItem] | None = None
    compositionField: CompositionField | None = None
    presenceField: PresenceField | None = None
    recursiveField: NotRoot | None = None
    userName: UserName | None = None
    notFalseField: Any | None = None


NotRoot.model_rebuild()
